package com.idm.agent.dl;

import com.idm.fotaagent.enabler.fumo.IDMFumoExtInterface;

/* loaded from: classes.dex */
public enum DLResultCode {
    SUCCESS(IDMDlInterface.IDM_REPORT_STATUS_SUCCESS, ""),
    INSUFFICIENT_STORAGE(IDMDlInterface.IDM_REPORT_STATUS_INSUFFICIENT_MEMORY, IDMDlInterface.IDM_FOTA_GENERIC_DOWNLOAD_FAILED_OUT_MEMORY),
    CANCELLED_BY_USER(IDMDlInterface.IDM_REPORT_STATUS_USER_CANCELLED, "401"),
    LOSSED_SERVICE(IDMDlInterface.IDM_REPORT_STATUS_LOSS_OF_SERVICE, IDMDlInterface.IDM_FOTA_GENERIC_UNDEFINED_ERROR),
    MISMATCHED_ATTRIBUTE(IDMDlInterface.IDM_REPORT_STATUS_ATTRIBUTE_MISMATCH, IDMDlInterface.IDM_FOTA_GENERIC_CORRUPTED_FW_UP),
    INVALID_DESCRIPTOR(IDMDlInterface.IDM_REPORT_STATUS_INVALID_DESCRIPTOR, IDMDlInterface.IDM_FOTA_GENERIC_UNDEFINED_ERROR),
    INVALID_DD_VERSION(IDMDlInterface.IDM_REPORT_STATUS_INVALID_DDVERSION, IDMDlInterface.IDM_FOTA_GENERIC_UNDEFINED_ERROR),
    ABORTED_BY_DEVICE(IDMDlInterface.IDM_REPORT_STATUS_DEVICE_ABORTED, "400"),
    NON_ACCEPTABLE_CONTENT(IDMDlInterface.IDM_REPORT_STATUS_NON_ACCEPTABLE_CONTENT, "405"),
    LOADER_ERROR(IDMDlInterface.IDM_REPORT_STATUS_LOADER_ERROR, IDMDlInterface.IDM_FOTA_GENERIC_BAD_URL),
    BLOCKED_BY_AFW(IDMDlInterface.IDM_REPORT_STATUS_BLOCKED_BY_AFW_POLICY, IDMFumoExtInterface.IDM_FOTA_GENERIC_BLOCKED_AFW_UPDATE_FAILED),
    BLOCKED_BY_MDM(IDMDlInterface.IDM_REPORT_STATUS_BLOCKED_BY_MDM_POLICY, IDMFumoExtInterface.IDM_FOTA_GENERIC_BLOCKED_MDM_UPDATE_FAILED),
    BLOCKED_BY_WIFI_BACKGROUND(IDMDlInterface.IDM_REPORT_STATUS_WIFIBACKGROUND_SESSION_FAILED, IDMFumoExtInterface.IDM_FOTA_GENERIC_WIFIBACKGROUND_SESSION_FAILED);

    private final String dmResultCode;
    private final String message;

    DLResultCode(String str, String str2) {
        this.message = str;
        this.dmResultCode = str2;
    }

    public String getDmResultCode() {
        return this.dmResultCode;
    }

    public String getMessage() {
        return this.message;
    }
}
