package l3;

import c3.InterfaceC0221a;
import i3.InterfaceC0494o;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import p.AbstractC0735a;
import r3.InterfaceC0802e;
import r3.InterfaceC0806i;

/* renamed from: l3.t, reason: case insensitive filesystem */
/* loaded from: classes.dex */
public final class C0695t extends d3.k implements InterfaceC0221a {

    /* renamed from: d, reason: collision with root package name */
    public final /* synthetic */ int f8221d;

    /* renamed from: e, reason: collision with root package name */
    public final /* synthetic */ C0701z f8222e;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public /* synthetic */ C0695t(C0701z c0701z, int i5) {
        super(0);
        this.f8221d = i5;
        this.f8222e = c0701z;
    }

    @Override // c3.InterfaceC0221a
    public final Object a() {
        K3.b bVar;
        K3.a aVar = null;
        C0701z c0701z = this.f8222e;
        switch (this.f8221d) {
            case 0:
                Collection collectionD = c0701z.d();
                ArrayList arrayList = new ArrayList(R2.o.C0(collectionD));
                Iterator it = collectionD.iterator();
                while (it.hasNext()) {
                    arrayList.add(new C0649E(c0701z, (InterfaceC0806i) it.next()));
                }
                return arrayList;
            case 1:
                return c0701z.g(c0701z.r().q().q0(), 1);
            case 2:
                a4.o oVarX = c0701z.r().X();
                d3.i.d("descriptor.staticScope", oVarX);
                return c0701z.g(oVarX, 1);
            case 3:
                int i5 = C0701z.f;
                Q3.b bVarQ = c0701z.q();
                C0698w c0698w = (C0698w) c0701z.f8244e.a();
                c0698w.getClass();
                InterfaceC0494o interfaceC0494o = AbstractC0645A.f8102b[0];
                Object objA = c0698w.f8103a.a();
                d3.i.d("<get-moduleData>(...)", objA);
                boolean z4 = bVarQ.f2232c;
                d4.i iVar = ((w3.e) objA).f9613a;
                InterfaceC0802e interfaceC0802eB = z4 ? iVar.b(bVarQ) : o4.a.e(iVar.f6530b, bVarQ);
                if (interfaceC0802eB != null) {
                    return interfaceC0802eB;
                }
                Class cls = c0701z.f8243d;
                w3.b bVarF = AbstractC0735a.f(cls);
                if (bVarF != null && (bVar = bVarF.f9609b) != null) {
                    aVar = (K3.a) bVar.f1289d;
                }
                switch (aVar == null ? -1 : AbstractC0699x.f8239a[aVar.ordinal()]) {
                    case -1:
                    case 6:
                        throw new Q2.d("Unresolved class: " + cls, 2);
                    case 0:
                    default:
                        throw new A0.c();
                    case 1:
                    case 2:
                    case 3:
                        throw new UnsupportedOperationException("Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: " + cls);
                    case 4:
                        throw new UnsupportedOperationException("This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: " + cls);
                    case 5:
                        throw new Q2.d("Unknown class: " + cls + " (kind = " + aVar + ')', 2);
                }
            case 4:
                return c0701z.g(c0701z.r().q().q0(), 2);
            case 5:
                a4.o oVarX2 = c0701z.r().X();
                d3.i.d("descriptor.staticScope", oVarX2);
                return c0701z.g(oVarX2, 2);
            case 6:
                if (c0701z.f8243d.isAnonymousClass()) {
                    return null;
                }
                Q3.b bVarQ2 = c0701z.q();
                if (bVarQ2.f2232c) {
                    return null;
                }
                return bVarQ2.b().b();
            default:
                return new C0698w(c0701z);
        }
    }
}
